using System.ComponentModel;

namespace Grc.ui.App.Enums {
    public enum ActionKey {
        [Description("all")]
        All,
        [Description("new")]
        New,
        [Description("edit")]
        Edit,
        [Description("delete")]
        Delete,
        [Description("import")]
        Import,
        [Description("export")]
        Export,
        [Description("search")]
        Search,
        [Description("units")]
        Units,
        [Description("ugroups")]
        UserGroups,
        [Description("ugroles")]
        UserRoles,
        [Description("departments")]
        Departments,
        [Description("separator")] 
        Separator,
        [Description("permissions")]
        Permissions,
        [Description("update")]
        Update,
        [Description("close")]
        Close,
        [Description("email")]
        Email,
        [Description("excel")]
        Excel,
        [Description("opsHome")]
        OpsHome,
        [Description("totalProposed")]
        TotalProposed,
        [Description("totalUnchanged")]
        TotalUnchanged,
        [Description("totalDueReview")]
        TotalDueReview,
        [Description("totalDormant")]
        TotalDormant,
        [Description("totalCancelled")]
        TotalCancelled,
        [Description("totalCompleted")]
        TotalCompleted,
        [Description("cashProcesses")]
        CashProcesses,
        [Description("walletProcesses")]
        WalletProcesses,
        [Description("paymentProcesses")]
        PaymentProcesses,
        [Description("reconProcesses")]
        ReconProcesses,
        [Description("customerExProcesses")]
        CustomerExProcesses,
        [Description("recordsProcesses")]
        RecordsProcesses,
        [Description("channelProcesses")]
        ChannelProcesses,
        [Description("accountSvcProcesses")]
        AccountSvcProcesses,
        [Description("complianceHome")]
        ComplianceHome,
        [Description("newType")]
        NewType,
        [Description("newCategory")]
        NewCategory,
        [Description("category-export")]
        CategoryExport,
        [Description("type-export")]
        TypeExport,
    }
}
