using System.ComponentModel;

namespace Grc.ui.App.Enums {
    public enum ActionKey {
        [Description("all")]
        All,
        [Description("new")]
        New,
        [Description("edit")]
        Edit,
        [Description("delete")]
        Delete,
        [Description("import")]
        Import,
        [Description("export")]
        Export,
        [Description("search")]
        Search,
        [Description("units")]
        Units,
        [Description("user-groups")]
        UserGroups,
        [Description("user-group-roles")]
        UserRoles,
        [Description("departments")]
        Departments,
        [Description("departments-new")]
        NewDepartment,
        [Description("responsibility-new")]
        NewResponsibility,
        [Description("separator")] 
        Separator,
        [Description("permissions")]
        Permissions,
        [Description("update")]
        Update,
        [Description("close")]
        Close,
        [Description("email")]
        Email,
        [Description("lock-account")]
        LockAccount,
        [Description("approve-user")]
        ApproveUser,
        [Description("password-user")]
        UserPassword,
        [Description("excel")]
        Excel,
        [Description("opsHome")]
        OpsHome,
        [Description("process-new")]
        ProcessNew,
        [Description("process-export")]
        ProcessExport,
        [Description("proposed-list")]
        TotalProposed,
        [Description("unchanged-list")]
        TotalUnchanged,
        [Description("due-review-list")]
        TotalDueReview,
        [Description("dormant-list")]
        TotalDormant,
        [Description("cancelled-list")]
        TotalCancelled,
        [Description("completed-list")]
        TotalCompleted,
        [Description("cashProcesses")]
        CashProcesses,
        [Description("walletProcesses")]
        WalletProcesses,
        [Description("paymentProcesses")]
        PaymentProcesses,
        [Description("reconProcesses")]
        ReconProcesses,
        [Description("customerExProcesses")]
        CustomerExProcesses,
        [Description("recordsProcesses")]
        RecordsProcesses,
        [Description("channelProcesses")]
        ChannelProcesses,
        [Description("accountSvcProcesses")]
        AccountSvcProcesses,
        [Description("complianceHome")]
        ComplianceHome,
        [Description("new-type")]
        NewType,
        [Description("type-export")]
        TypeExport,
        [Description("new-category")]
        NewCategory,
        [Description("category-export")]
        CategoryExport,
        [Description("new-authority")]
        NewAuthority,
        [Description("authority-export")]
        AuthorityExport,
        [Description("policy-new")]
        NewPolicy,
        [Description("policy-export")]
        ExportPolicy,
        [Description("policy-task")]
        PolicyTask,
        [Description("policy-task-new")]
        NewPolicyTask,
        [Description("policy-task-mail")]
        PolicyTaskMail,
        [Description("policy-task-export")]
        PolicyTaskExport,
        [Description("admin-home")]
        AdminHome,
        [Description("act-new")]
        RegulatoryActNew,
        [Description("oblig-map")]
        ObligationMap,
        [Description("oblig-register")]
        ObligationRegister,
        [Description("new-user")]
        NewUser,
        [Description("edit-user")]
        EditUser,
        [Description("delete-user")]
        DeleteUser,
        [Description("user-units")]
        UserUnits,
        [Description("user-departments")]
        UserDepartments,
        [Description("new-set")]
        NewSet,
        [Description("edit-set")]
        EditSet,
        [Description("delete-set")]
        DeleteSet,
        [Description("new-role-group")]
        RoleGroupNew,
        [Description("support-home")]
        SupportHome,
        [Description("new-role")]
        RoleNew,
    }
}
