using System.ComponentModel;

namespace Grc.ui.App.Enums {
    public enum ActionKey {
        [Description("all")]
        All,
        [Description("new")]
        New,
        [Description("edit")]
        Edit,
        [Description("delete")]
        Delete,
        [Description("import")]
        Import,
        [Description("export")]
        Export,
        [Description("search")]
        Search,
        [Description("units")]
        Units,
        [Description("ugroups")]
        UserGroups,
        [Description("ugroles")]
        UserRoles,
        [Description("departments")]
        Departments,
        [Description("departments-new")]
        NewDepartment,
        [Description("responsibility-new")]
        NewResponsibility,
        [Description("separator")] 
        Separator,
        [Description("permissions")]
        Permissions,
        [Description("update")]
        Update,
        [Description("close")]
        Close,
        [Description("email")]
        Email,
        [Description("excel")]
        Excel,
        [Description("opsHome")]
        OpsHome,
        [Description("totalProposed")]
        TotalProposed,
        [Description("totalUnchanged")]
        TotalUnchanged,
        [Description("totalDueReview")]
        TotalDueReview,
        [Description("totalDormant")]
        TotalDormant,
        [Description("totalCancelled")]
        TotalCancelled,
        [Description("totalCompleted")]
        TotalCompleted,
        [Description("cashProcesses")]
        CashProcesses,
        [Description("walletProcesses")]
        WalletProcesses,
        [Description("paymentProcesses")]
        PaymentProcesses,
        [Description("reconProcesses")]
        ReconProcesses,
        [Description("customerExProcesses")]
        CustomerExProcesses,
        [Description("recordsProcesses")]
        RecordsProcesses,
        [Description("channelProcesses")]
        ChannelProcesses,
        [Description("accountSvcProcesses")]
        AccountSvcProcesses,
        [Description("complianceHome")]
        ComplianceHome,
        [Description("new-type")]
        NewType,
        [Description("type-export")]
        TypeExport,
        [Description("new-category")]
        NewCategory,
        [Description("category-export")]
        CategoryExport,
        [Description("new-authority")]
        NewAuthority,
        [Description("authority-export")]
        AuthorityExport,
        [Description("policy-new")]
        NewPolicy,
        [Description("policy-export")]
        ExportPolicy,
        [Description("policy-task")]
        PolicyTask,
        [Description("policy-task-new")]
        NewPolicyTask,
        [Description("policy-task-mail")]
        PolicyTaskMail,
        [Description("policy-task-export")]
        PolicyTaskExport,
    }
}
