using AutoMapper;
using Grc.Middleware.Api.Data.Entities.Compliance.Audits;
using Grc.Middleware.Api.Data.Entities.Compliance.Regulations;
using Grc.Middleware.Api.Data.Entities.Compliance.Returns;
using Grc.Middleware.Api.Data.Entities.Logging;
using Grc.Middleware.Api.Data.Entities.Operations.Processes;
using Grc.Middleware.Api.Data.Entities.Org;
using Grc.Middleware.Api.Data.Entities.Support;
using Grc.Middleware.Api.Data.Entities.System;
using Grc.Middleware.Api.Enums;
using Grc.Middleware.Api.Http.Requests;
using Grc.Middleware.Api.Http.Responses;

namespace Grc.Middleware.Api.Helpers {

    public class MappingProfile : Profile {

        public MappingProfile() {

            CreateMap<RegistrationRequest, Company>()
                .ForMember(co => co.Id, reg => reg.MapFrom(o => 0))
                .ForMember(co => co.CompanyName, reg => reg.MapFrom(o => (o.CompanyName ?? string.Empty).Trim()))
                .ForMember(co => co.ShortName, reg => reg.MapFrom(o => (o.Alias ?? string.Empty).Trim()))
                .ForMember(co => co.RegistrationNumber, reg => reg.MapFrom(o => (o.RegNumber ?? string.Empty).Trim()))
                .ForMember(co => co.SystemLanguage, reg => reg.MapFrom(o => o.Language))
                .ForMember(co => co.IsDeleted, reg => reg.MapFrom(o => false))
                .ForMember(co => co.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(co => co.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(co => co.LastModifiedBy, reg => reg.MapFrom(o => (o.ModifiedBy ?? string.Empty).Trim()))
                .ForMember(co => co.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn));
        
            //..map user from registration
            CreateMap<RegistrationRequest, SystemUser>()
                .ForMember(us => us.Id, reg => reg.MapFrom(o => 0))
                .ForMember(us => us.FirstName, reg => reg.MapFrom(o => (o.FirstName ?? string.Empty).Trim()))
                .ForMember(us => us.LastName, reg => reg.MapFrom(o => (o.LastName ?? string.Empty).Trim()))
                .ForMember(us => us.OtherName, reg => reg.MapFrom(o => (o.MiddleName ?? string.Empty).Trim()))
                .ForMember(us => us.EmailAddress, reg => reg.MapFrom(o => (o.Email ?? string.Empty).Trim()))
                .ForMember(us => us.Username, reg => reg.MapFrom(o => (o.UserName ?? string.Empty).Trim()))
                .ForMember(us => us.PasswordHash, reg => reg.MapFrom(o => (o.Password ?? string.Empty).Trim()))
                .ForMember(us => us.PFNumber, reg => reg.MapFrom(o => (o.PFNumber ?? string.Empty).Trim()))
                .ForMember(us => us.BranchSolId, reg => reg.MapFrom(o => (o.SolId ?? "MAIN").Trim()))
                .ForMember(us => us.PhoneNumber, reg => reg.MapFrom(o => o.PhoneNumber))
                .ForMember(us => us.DepartmentUnit, reg => reg.MapFrom(o => o.UnitCode))
                .ForMember(us => us.RoleId, reg => reg.MapFrom(o => o.RoleId))
                .ForMember(us => us.DepartmentId, reg => reg.MapFrom(o => o.DepartmentId))
                .ForMember(us => us.IsActive, reg => reg.MapFrom(o => true))
                .ForMember(us => us.IsVerified, reg => reg.MapFrom(o => true))
                .ForMember(us => us.IsDeleted, reg => reg.MapFrom(o => false))
                .ForMember(us => us.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(us => us.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(us => us.LastModifiedBy, reg => reg.MapFrom(o => (o.ModifiedBy ?? string.Empty).Trim()))
                .ForMember(us => us.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn));

            //..map user from registration
            CreateMap<SystemUser, AuthenticationResponse>()
                .ForMember(a => a.UserId, reg => reg.MapFrom(o => o.Id))
                .ForMember(a => a.FirstName, reg => reg.MapFrom(o => (o.FirstName ?? string.Empty).Trim()))
                .ForMember(a => a.LastName, reg => reg.MapFrom(o => (o.LastName ?? string.Empty).Trim()))
                .ForMember(a => a.MiddleName, reg => reg.MapFrom(o => (o.OtherName ?? string.Empty).Trim()))
                .ForMember(a => a.EmailAddress, reg => reg.MapFrom(o => (o.EmailAddress ?? string.Empty).Trim()))
                .ForMember(a => a.Username, reg => reg.MapFrom(o => (o.Username ?? string.Empty).Trim()))
                .ForMember(a => a.Password, reg => reg.MapFrom(o => (o.PasswordHash ?? string.Empty).Trim()))
                .ForMember(a => a.PFNumber, reg => reg.MapFrom(o => (o.PFNumber ?? string.Empty).Trim()))
                .ForMember(a => a.SolId, reg => reg.MapFrom(o => (o.BranchSolId ?? "MAIN").Trim()))
                .ForMember(a => a.PhoneNumber, reg => reg.MapFrom(o => o.PhoneNumber))
                .ForMember(a => a.RoleId, reg => reg.MapFrom(o => o.RoleId))
                .ForMember(a => a.RoleName, reg => reg.MapFrom(o => o.Role.RoleName))
                .ForMember(a => a.DepartmentId, reg => reg.MapFrom(o => o.DepartmentId))
                .ForMember(a => a.DepartmentCode, reg => reg.MapFrom(o => o.Department.DepartmentCode))
                .ForMember(a => a.DepartmentName, reg => reg.MapFrom(o => o.Department.DepartmentName))
                .ForMember(a => a.UnitCode, reg => reg.MapFrom(o => o.DepartmentUnit))
                .ForMember(a => a.IsActive, reg => reg.MapFrom(o => o.IsActive))
                .ForMember(a => a.IsVerified, reg => reg.MapFrom(o => o.IsVerified))
                .ForMember(a => a.IsApproved, reg => reg.MapFrom(o => o.IsApproved))
                .ForMember(a => a.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(a => a.RedirectUrl, reg => reg.MapFrom(o => string.Empty))
                .ForMember(a => a.Favourites, reg => reg.MapFrom(o => new List<string>()))
                .ForMember(a => a.Views, reg => reg.MapFrom(o => new List<string>()))
                .ForMember(a => a.Claims, reg => reg.MapFrom(o => new Dictionary<string, object>()));

            //..map user from registration
            CreateMap<UserRecordRequest, SystemUser>()
                .ForMember(a => a.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(a => a.FirstName, reg => reg.MapFrom(o => (o.FirstName ?? string.Empty).Trim()))
                .ForMember(a => a.LastName, reg => reg.MapFrom(o => (o.LastName ?? string.Empty).Trim()))
                .ForMember(a => a.OtherName, reg => reg.MapFrom(o => (o.MiddleName ?? string.Empty).Trim()))
                .ForMember(a => a.EmailAddress, reg => reg.MapFrom(o => (o.EmailAddress ?? string.Empty).Trim()))
                .ForMember(a => a.Username, reg => reg.MapFrom(o => (o.UserName ?? string.Empty).Trim()))
                .ForMember(a => a.PasswordHash, reg => reg.MapFrom(o => (o.Password ?? string.Empty).Trim()))
                .ForMember(a => a.PFNumber, reg => reg.MapFrom(o => (o.PFNumber ?? string.Empty).Trim()))
                .ForMember(a => a.BranchSolId, reg => reg.MapFrom(o => (o.SolId ?? "MAIN").Trim()))
                .ForMember(a => a.PhoneNumber, reg => reg.MapFrom(o => o.PhoneNumber))
                .ForMember(a => a.RoleId, reg => reg.MapFrom(o => o.RoleId))
                .ForMember(a => a.DepartmentId, reg => reg.MapFrom(o => o.DepartmentId))
                .ForMember(a => a.DepartmentUnit, reg => reg.MapFrom(o => o.UnitCode))
                .ForMember(a => a.IsActive, reg => reg.MapFrom(o => o.IsActive))
                .ForMember(a => a.IsLoggedIn, reg => reg.MapFrom(o => false))
                .ForMember(a => a.IsVerified, reg => reg.MapFrom(o => o.IsVerified))
                .ForMember(a => a.IsApproved, reg => reg.MapFrom(o => o.IsApproved))
                .ForMember(a => a.IsDeleted, reg => reg.MapFrom(o => !o.IsActive))
                .ForMember(a => a.IsApproved, reg => reg.MapFrom(o => o.IsApproved))
                .ForMember(a => a.CreatedOn, reg => reg.MapFrom(o => DateTime.Now))
                .ForMember(a => a.CreatedBy, reg => reg.MapFrom(o => o.CreatedBy))
                .ForMember(a => a.LastModifiedOn, reg => reg.MapFrom(o => DateTime.Now))
                .ForMember(a => a.LastModifiedBy, reg => reg.MapFrom(o => o.CreatedBy));

            //..map quick actions
            CreateMap<UserQuickAction, QuickActionResponse>()
                .ForMember(a => a.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(a => a.Label, reg => reg.MapFrom(o => (o.Label ?? string.Empty).Trim()))
                .ForMember(a => a.IconClass, reg => reg.MapFrom(o => (o.IconClass ?? string.Empty).Trim()))
                .ForMember(a => a.Controller, reg => reg.MapFrom(o => (o.Controller ?? string.Empty).Trim()))
                .ForMember(a => a.Action, reg => reg.MapFrom(o => (o.Action ?? string.Empty).Trim()))
                .ForMember(a => a.Area, reg => reg.MapFrom(o => (o.Area ?? string.Empty).Trim()))
                .ForMember(a => a.CssClass, reg => reg.MapFrom(o => (o.CssClass ?? string.Empty).Trim()));

            //..map pinned items
            CreateMap<UserPinnedItem, PinnedItemResponse>()
                .ForMember(a => a.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(a => a.Label, reg => reg.MapFrom(o => (o.Label ?? string.Empty).Trim()))
                .ForMember(a => a.IconClass, reg => reg.MapFrom(o => (o.IconClass ?? string.Empty).Trim()))
                .ForMember(a => a.Controller, reg => reg.MapFrom(o => (o.Controller ?? string.Empty).Trim()))
                .ForMember(a => a.Action, reg => reg.MapFrom(o => (o.Action ?? string.Empty).Trim()))
                .ForMember(a => a.Area, reg => reg.MapFrom(o => (o.Area ?? string.Empty).Trim()))
                .ForMember(a => a.CssClass, reg => reg.MapFrom(o => (o.CssClass ?? string.Empty).Trim()));

            //..map system permissions
            CreateMap<SystemPermission, PermissionResponse>()
                .ForMember(a => a.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(a => a.PermissionName, reg => reg.MapFrom(o => (o.PermissionName ?? string.Empty).Trim()))
                .ForMember(a => a.PermissionDescription, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()));

            //..map pinned items
            CreateMap<ErrorRequest, SystemError>()
                .ForMember(e => e.CompanyId, reg => reg.MapFrom(o => o.CompanyId))
                .ForMember(e => e.ErrorMessage, reg => reg.MapFrom(o => (o.Message ?? string.Empty).Trim()))
                .ForMember(e => e.ErrorSource, reg => reg.MapFrom(o => (o.Source ?? string.Empty).Trim()))
                .ForMember(e => e.StackTrace, reg => reg.MapFrom(o => (o.StackTrace ?? string.Empty).Trim()))
                .ForMember(e => e.Severity, reg => reg.MapFrom(o => (o.Severity ?? string.Empty).Trim()))
                .ForMember(e => e.Assigned, reg => reg.MapFrom(o => false))
                .ForMember(e => e.IsDeleted, reg => reg.MapFrom(o => false))
                .ForMember(e => e.FixStatus, reg => reg.MapFrom(o => "OPEN"))
                .ForMember(e => e.ReportedOn, reg => reg.MapFrom(o => DateTime.Now))
                .ForMember(e => e.CreatedOn, reg => reg.MapFrom(o => DateTime.Now))
                .ForMember(e => e.CreatedBy, reg => reg.MapFrom(o => $"{o.UserId}"))
                .ForMember(e => e.IsUserReported, reg => reg.MapFrom(o => false));

             CreateMap<ActivityLog, ActivityLogResponse>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.UserId, reg => reg.MapFrom(o => o.UserId))
                .ForMember(r => r.UserFirstName, reg => reg.MapFrom(o => (o.User.FirstName ?? string.Empty).Trim()))
                .ForMember(r => r.UserLastName, reg => reg.MapFrom(o => (o.User.LastName ?? string.Empty).Trim()))
                .ForMember(r => r.UserEmail, reg => reg.MapFrom(o => (o.User.EmailAddress ?? string.Empty).Trim()))
                .ForMember(r => r.EntityId, reg => reg.MapFrom(o => o.EntityId))
                .ForMember(r => r.EntityName, reg => reg.MapFrom(o => (o.EntityName ?? string.Empty).Trim()))
                .ForMember(r => r.TypeId, reg => reg.MapFrom(o => o.TypeId))
                .ForMember(r => r.TypeDescription, reg => reg.MapFrom(o => (o.ActivityType.Description ?? string.Empty).Trim()))
                .ForMember(r => r.IpAddress, reg => reg.MapFrom(o => (o.IpAddress ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.Comment, reg => reg.MapFrom(o => (o.Comment ?? string.Empty).Trim()));
            
            CreateMap<Department, DepartmentResponse>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.BranchId, reg => reg.MapFrom(o => o.BranchId))
                .ForMember(r => r.Branch, reg => reg.MapFrom(o => (o.Branch.BranchName ?? string.Empty).Trim()))
                .ForMember(r => r.DepartmentCode, reg => reg.MapFrom(o => (o.DepartmentCode ?? string.Empty).Trim()))
                .ForMember(r => r.DepartmentName, reg => reg.MapFrom(o => (o.DepartmentName?? string.Empty).Trim()))
                .ForMember(r => r.DepartmentAlias, reg => reg.MapFrom(o => o.Alias))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatdOn, reg => reg.MapFrom(o => o.CreatedOn));

            CreateMap<DepartmentUnit, DepartmentUnitResponse>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.DepartmentId, reg => reg.MapFrom(o => o.DepartmentId))
                .ForMember(r => r.Department, reg => reg.MapFrom(o => (o.Department.DepartmentName ?? string.Empty).Trim()))
                .ForMember(r => r.UnitName, reg => reg.MapFrom(o => (o.UnitName  ?? string.Empty).Trim()))
                .ForMember(r => r.UnitCode, reg => reg.MapFrom(o => (o.UnitCode?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatdOn, reg => reg.MapFrom(o => o.CreatedOn));
            
            CreateMap<Branch, BranchResponse>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.CompanyId, reg => reg.MapFrom(o => o.CompanyId))
                .ForMember(r => r.CompanyName, reg => reg.MapFrom(o => (o.Company.CompanyName ?? string.Empty).Trim()))
                .ForMember(r => r.BranchName, reg => reg.MapFrom(o => (o.BranchName ?? string.Empty).Trim()))
                .ForMember(r => r.SolId, reg => reg.MapFrom(o => (o.SolId  ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => (o.LastModifiedBy  ?? string.Empty).Trim()))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.LastModifiedOn));

            CreateMap<AuthorityRequest, Authority>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.AuthorityName, reg => reg.MapFrom(o => (o.AuthorityName ?? string.Empty).Trim()))
                .ForMember(r => r.AuthorityAlias, reg => reg.MapFrom(o => (o.AuthorityAlias ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ReturnTypeRequest, ReturnType>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.TypeName, reg => reg.MapFrom(o => (o.TypeName ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ResponsebilityRequest, Responsebility>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.ContactName, reg => reg.MapFrom(o => (o.ContactName ?? string.Empty).Trim()))
                .ForMember(r => r.ContactPhone, reg => reg.MapFrom(o => (o.ContactPhone ?? string.Empty).Trim()))
                .ForMember(r => r.ContactEmail, reg => reg.MapFrom(o => (o.ContactEmail ?? string.Empty).Trim()))
                .ForMember(r => r.ContactPosition, reg => reg.MapFrom(o => (o.ContactPosition ?? string.Empty).Trim()))
                .ForMember(r => r.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(r => r.DepartmentId, reg => reg.MapFrom(o => o.DepartmentId))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<FrequencyRequest, Frequency>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.FrequencyName, reg => reg.MapFrom(o => (o.FrequencyName ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ReturnTypeRequest, ReturnType>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.TypeName, reg => reg.MapFrom(o => (o.TypeName ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<NotificationRequest, SubmissionNotification>()
               .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
               .ForMember(r => r.SentTo, reg => reg.MapFrom(o => (o.SentTo ?? string.Empty).Trim()))
               .ForMember(r => r.CarbonCopy, reg => reg.MapFrom(o => (o.CarbonCopy ?? string.Empty).Trim()))
               .ForMember(r => r.BlindCopy, reg => reg.MapFrom(o => (o.BlindCopy ?? string.Empty).Trim()))
               .ForMember(r => r.Message, reg => reg.MapFrom(o => (o.Message ?? string.Empty).Trim()))
               .ForMember(r => r.SubmissionId, reg => reg.MapFrom(o => o.SubmissionId))
               .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
               .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
               .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
               .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
               .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<DocumentTypeRequest, RegulatoryDocumentType>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.DocumentType, reg => reg.MapFrom(o => (o.DocumentType ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<RegulatoryCategoryRequest, RegulatoryCategory>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.CategoryName, reg => reg.MapFrom(o => (o.CategoryName ?? string.Empty).Trim()))
                .ForMember(r => r.Comments, reg => reg.MapFrom(o => (o.Comments ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<AuditExceptionRequest, AuditException>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.Obligation, reg => reg.MapFrom(o => (o.Obligation ?? string.Empty).Trim()))
                .ForMember(r => r.CorrectiveAction, reg => reg.MapFrom(o => (o.CorrectiveAction ?? string.Empty).Trim()))
                .ForMember(r => r.ExceptionNoted, reg => reg.MapFrom(o => (o.ExceptionNoted ?? string.Empty).Trim()))
                .ForMember(r => r.RemediationPlan, reg => reg.MapFrom(o => (o.RemediationPlan ?? string.Empty).Trim()))
                .ForMember(r => r.TargetDate, reg => reg.MapFrom(o => o.TargetDate))
                .ForMember(r => r.RiskAssessment, reg => reg.MapFrom(o => (o.RiskAssessment ?? string.Empty).Trim()))
                .ForMember(r => r.RiskRating, reg => reg.MapFrom(o => o.RiskRating))
                .ForMember(r => r.Status, reg => reg.MapFrom(o => o.LastUpdated))
                .ForMember(r => r.LastUpdated, reg => reg.MapFrom(o => o.LastUpdated))
                .ForMember(r => r.AuditTaskId, reg => reg.MapFrom(o => o.AuditTaskId))
                .ForMember(r => r.AuditReportId, reg => reg.MapFrom(o => o.AuditReportId))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<AuditRequest, Audit>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.AuditName, reg => reg.MapFrom(o => (o.AuditName ?? string.Empty).Trim()))
                .ForMember(r => r.Priority, reg => reg.MapFrom(o => (o.Priority ?? string.Empty).Trim()))
                .ForMember(r => r.Category, reg => reg.MapFrom(o => (o.Category ?? string.Empty).Trim()))
                .ForMember(r => r.SubCategory, reg => reg.MapFrom(o => (o.SubCategory ?? string.Empty).Trim()))
                .ForMember(r => r.NumberOfReports, reg => reg.MapFrom(o => o.NumberOfReports))
                .ForMember(r => r.Attachement, reg => reg.MapFrom(o => (o.Attachement ?? string.Empty).Trim()))
                .ForMember(r => r.AuthorityId, reg => reg.MapFrom(o => o.AuthorityId))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<AuditTaskRequest, AuditTask>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.TaskName, reg => reg.MapFrom(o => (o.TaskName ?? string.Empty).Trim()))
                .ForMember(r => r.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(r => r.Status, reg => reg.MapFrom(o => (o.Status ?? string.Empty).Trim()))
                .ForMember(r => r.DueDate, reg => reg.MapFrom(o => o.DueDate))
                .ForMember(r => r.AuditId, reg => reg.MapFrom(o => o.AuditId))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<StatutoryRegulationRequest, StatutoryRegulation>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.Code, reg => reg.MapFrom(o => (o.Code ?? string.Empty).Trim()))
                .ForMember(r => r.RegulatoryName, reg => reg.MapFrom(o => (o.RegulatoryName ?? string.Empty).Trim()))
                .ForMember(r => r.TypeId, reg => reg.MapFrom(o => o.TypeId))
                .ForMember(r => r.AuthorityId, reg => reg.MapFrom(o => o.AuthorityId))
                .ForMember(r => r.CategoryId, reg => reg.MapFrom(o => o.CategoryId))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<StatutoryArticleRequest, StatutoryArticle>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.StatuteId, reg => reg.MapFrom(o => o.StatutoryId))
                .ForMember(r => r.Article, reg => reg.MapFrom(o => (o.Section ?? string.Empty).Trim()))
                .ForMember(r => r.Summery, reg => reg.MapFrom(o => (o.Summery ?? string.Empty).Trim()))
                .ForMember(r => r.Comments, reg => reg.MapFrom(o => (o.Comments ?? string.Empty).Trim()))
                .ForMember(r => r.ObligationOrRequirement, reg => reg.MapFrom(o => o.Obligation))
                .ForMember(r => r.IsMandatory, reg => reg.MapFrom(o => o.IsMandatory))
                .ForMember(r => r.ExcludeFromCompliance, reg => reg.MapFrom(o => o.ExcludeFromCompliance))
                .ForMember(r => r.Coverage, reg => reg.MapFrom(o => o.Coverage))
                .ForMember(r => r.IsCovered, reg => reg.MapFrom(o => o.IsCovered))
                .ForMember(r => r.FrequencyId, reg => reg.MapFrom(o => o.FrequencyId))
                .ForMember(r => r.OwnerId, reg => reg.MapFrom(o => o.OwnerId))
                .ForMember(r => r.ComplianceAssurance, reg => reg.MapFrom(o => o.ComplianceAssurance))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ArticleRevisionRequest, ArticleRevision>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.ArticleId, reg => reg.MapFrom(o => o.ArticleId))
                .ForMember(r => r.Section, reg => reg.MapFrom(o => (o.Section ?? string.Empty).Trim()))
                .ForMember(r => r.Summery, reg => reg.MapFrom(o => (o.Summery ?? string.Empty).Trim()))
                .ForMember(r => r.Comments, reg => reg.MapFrom(o => (o.Comments ?? string.Empty).Trim()))
                .ForMember(r => r.Revision, reg => reg.MapFrom(o => o.Revision))
                .ForMember(r => r.ReviewedOn, reg => reg.MapFrom(o => o.ReviewedOn))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ReturnSubmissionRequest, ReturnSubmission>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.Status, reg => reg.MapFrom(o => o.Status))
                
                .ForMember(r => r.ReturnId, reg => reg.MapFrom(o => o.ReturnId))
                .ForMember(r => r.Deadline, reg => reg.MapFrom(o => o.Deadline))
                .ForMember(r => r.SubmissionDate, reg => reg.MapFrom(o => o.SubmissionDate))
                .ForMember(r => r.FilePath, reg => reg.MapFrom(o => o.FilePath))
                .ForMember(r => r.SubmittedBy, reg => reg.MapFrom(o => o.SubmittedBy))
                .ForMember(r => r.IsBreached, reg => reg.MapFrom(o => o.IsBreached))
                .ForMember(r => r.BreachReason, reg => reg.MapFrom(o => o.BreachReason))
                .ForMember(r => r.Comments, reg => reg.MapFrom(o => o.Comments))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => o.CreatedBy))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ReturnRequest, ReturnReport>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.ReturnName, reg => reg.MapFrom(o => (o.ReturnName ?? string.Empty).Trim()))
                .ForMember(r => r.TypeId, reg => reg.MapFrom(o => o.TypeId))
                .ForMember(r => r.FrequencyId, reg => reg.MapFrom(o => o.FrequencyId))
                .ForMember(r => r.ArticleId, reg => reg.MapFrom(o => o.ArticleId))
                .ForMember(r => r.AuthorityId, reg => reg.MapFrom(o => o.AuthorityId))
                .ForMember(r => r.DepartmentId, reg => reg.MapFrom(o => o.DepartmentId))
                .ForMember(r => r.Comments, reg => reg.MapFrom(o => (o.Comments ?? string.Empty).Trim()));

            CreateMap<PolicyDocumentRequest, RegulatoryDocument>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.DocumentName, reg => reg.MapFrom(o => (o.DocumentName ?? string.Empty).Trim()))
                .ForMember(r => r.Status, reg => reg.MapFrom(o => (o.DocumentStatus ?? string.Empty).Trim()))
                .ForMember(r => r.ApprovedBy, reg => reg.MapFrom(o => (o.ApprovedBy ?? string.Empty).Trim()))
                .ForMember(r => r.ApprovalDate, reg => reg.MapFrom(o => o.ApprovalDate))
                .ForMember(r => r.PolicyAligned, reg => reg.MapFrom(o => o.IsLocked))
                .ForMember(r => r.LastRevisionDate, reg => reg.MapFrom(o => o.LastRevisionDate))
                .ForMember(r => r.FrequencyId, reg => reg.MapFrom(o => o.FrequencyId))
                .ForMember(r => r.NextRevisionDate, reg => reg.MapFrom(o => o.NextRevisionDate))
                .ForMember(r => r.DocumentTypeId, reg => reg.MapFrom(o => o.DocumentTypeId))
                .ForMember(r => r.ResponsibilityId, reg => reg.MapFrom(o => o.ResponsibilityId))
                .ForMember(r => r.Comments, reg => reg.MapFrom(o => (o.Comments ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ProcessTypeRequest, ProcessType>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.TypeName, reg => reg.MapFrom(o => (o.TypeName ?? string.Empty).Trim()))
                .ForMember(r => r.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ProcessRequest, OperationProcess>()
                .ForMember(p => p.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(p => p.ProcessName, reg => reg.MapFrom(o => (o.ProcessName ?? string.Empty).Trim()))
                .ForMember(p => p.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(p => p.CurrentVersion, reg => reg.MapFrom(o => (o.CurrentVersion ?? string.Empty).Trim()))
                .ForMember(p => p.FileName, reg => reg.MapFrom(o => (o.FileName ?? string.Empty).Trim()))
                .ForMember(p => p.EffectiveDate, reg => reg.MapFrom(o => o.EffectiveDate))
                .ForMember(p => p.LastUpdated, reg => reg.MapFrom(o => o.LastUpdated))
                .ForMember(p => p.ProcessStatus, reg => reg.MapFrom(o => (o.ProcessStatus ?? string.Empty).Trim().ToUpper()))
                .ForMember(p => p.TypeId, reg => reg.MapFrom(o => o.TypeId))
                .ForMember(p => p.UnitId, reg => reg.MapFrom(o => o.UnitId))
                .ForMember(p => p.ResponsibilityId, reg => reg.MapFrom(o => o.OwnerId))
                .ForMember(p => p.ReasonOnhold, reg => reg.MapFrom(o => (o.OnholdReason ?? string.Empty).Trim()))
                .ForMember(p => p.NeedsBranchReview, reg => reg.MapFrom(o => o.NeedsBranchReview))
                .ForMember(p => p.NeedsCreditReview, reg => reg.MapFrom(o => o.NeedsCreditReview))
                .ForMember(p => p.NeedsTreasuryReview, reg => reg.MapFrom(o => o.NeedsTreasuryReview))
                .ForMember(p => p.NeedsFintechReview, reg => reg.MapFrom(o => o.NeedsFintechReview))
                .ForMember(p => p.IsLockProcess, reg => reg.MapFrom(o => o.IsLockProcess))
                .ForMember(p => p.UnlockReason, reg => reg.MapFrom(o => (o.UnlockReason ?? string.Empty).Trim()))
                .ForMember(p => p.Comments, reg => reg.MapFrom(o => (o.Comments ?? string.Empty).Trim()))
                .ForMember(p => p.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(p => p.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(p => p.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(p => p.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(p => p.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ProcessTaskRequest, ProcessTask>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.TaskName, reg => reg.MapFrom(o => (o.TaskName ?? string.Empty).Trim()))
                .ForMember(r => r.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(r => r.Status, reg => reg.MapFrom(o => (o.Status ?? string.Empty).Trim()))
                .ForMember(r => r.DueDate, reg => reg.MapFrom(o => o.DueDate))
                .ForMember(r => r.ProcessId, reg => reg.MapFrom(o => o.ProcessId))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ProcessActivityRequest, ProcessActivity>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.Activity, reg => reg.MapFrom(o => (o.Activity ?? string.Empty).Trim()))
                .ForMember(r => r.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(r => r.ProcessId, reg => reg.MapFrom(o => o.ProcessId))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ProcessTagRequest, ProcessTag>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.TagName, reg => reg.MapFrom(o => (o.TagName ?? string.Empty).Trim()))
                .ForMember(r => r.Description, reg => reg.MapFrom(o => (o.TagDescription ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => (o.ModifiedBy ?? string.Empty).Trim()))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<ProcessGroupRequest, ProcessGroup>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.GroupName, reg => reg.MapFrom(o => (o.GroupName ?? string.Empty).Trim()))
                .ForMember(r => r.Description, reg => reg.MapFrom(o => (o.GroupDescription ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<RoleGroupRequest, SystemRoleGroup>()
               .ForMember(p => p.Id, reg => reg.MapFrom(o => o.Id))
               .ForMember(p => p.GroupName, reg => reg.MapFrom(o => (o.GroupName ?? string.Empty).Trim()))
               .ForMember(p => p.Description, reg => reg.MapFrom(o => (o.GroupDescription ?? string.Empty).Trim()))
               .ForMember(p => p.GroupCategory, reg => reg.MapFrom(o => o.GroupCategory))
               .ForMember(p => p.Scope, reg => reg.MapFrom(o => o.GroupScope))
               .ForMember(p => p.Department, reg => reg.MapFrom(o => (o.DepartmentName ?? string.Empty).Trim()))
               .ForMember(p => p.Type, reg => reg.MapFrom(o => o.Type))
               .ForMember(p => p.IsApproved, reg => reg.MapFrom(o => o.IsApproved))
               .ForMember(p => p.IsVerified, reg => reg.MapFrom(o => o.IsVerified))
               .ForMember(p => p.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
               .ForMember(p => p.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
               .ForMember(p => p.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
               .ForMember(p => p.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
               .ForMember(p => p.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<RoleRequest, SystemRole>()
               .ForMember(p => p.Id, reg => reg.MapFrom(o => o.Id))
               .ForMember(p => p.RoleName, reg => reg.MapFrom(o => (o.RoleName ?? string.Empty).Trim()))
               .ForMember(p => p.Description, reg => reg.MapFrom(o => (o.RoleDescription ?? string.Empty).Trim()))
               .ForMember(p => p.GroupId, reg => reg.MapFrom(o => o.GroupId))
               .ForMember(p => p.IsApproved, reg => reg.MapFrom(o => o.IsApproved))
               .ForMember(p => p.IsVerified, reg => reg.MapFrom(o => o.IsVerified))
               .ForMember(p => p.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
               .ForMember(p => p.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
               .ForMember(p => p.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
               .ForMember(p => p.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
               .ForMember(p => p.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<SystemRoleGroup, RoleGroupResponse>()
               .ForMember(p => p.Id, reg => reg.MapFrom(o => o.Id))
               .ForMember(p => p.GroupName, reg => reg.MapFrom(o => (o.GroupName ?? string.Empty).Trim()))
               .ForMember(p => p.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
               .ForMember(p => p.GroupCategory, reg => reg.MapFrom(o => (o.GroupCategory ?? string.Empty).Trim()))
               .ForMember(p => p.GroupScope, reg => reg.MapFrom(o => o.Scope.Equals(GroupScope.SYSTEM) ? "System Role Group" : "Department Role Group"))
               .ForMember(p => p.GroupType, reg => reg.MapFrom(o => o.Type.Equals(RoleGroup.SYSTEM) ? "System Group" : "Custom Group"))
               .ForMember(p => p.DepartmentName, reg => reg.MapFrom(o => (o.Department ?? string.Empty).Trim()))
               .ForMember(p => p.IsApproved, reg => reg.MapFrom(o => o.IsApproved))
               .ForMember(p => p.IsVerified, reg => reg.MapFrom(o => o.IsVerified))
               .ForMember(p => p.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
               .ForMember(p => p.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
               .ForMember(p => p.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
               .ForMember(p => p.ModifiedBy, reg => reg.MapFrom(o => o.LastModifiedBy ?? string.Empty))
               .ForMember(p => p.ModifiedOn, reg => reg.MapFrom(o => o.LastModifiedOn ?? o.CreatedOn))
               .ForMember(p => p.Roles, reg => reg.MapFrom(o => o.Roles));

            CreateMap<SystemRole, RoleResponse>()
              .ForMember(p => p.Id, reg => reg.MapFrom(o => o.Id))
              .ForMember(p => p.RoleName, reg => reg.MapFrom(o => (o.RoleName ?? string.Empty).Trim()))
              .ForMember(p => p.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
              .ForMember(p => p.GroupId, reg => reg.MapFrom(o => o.GroupId))
              .ForMember(p => p.GroupName, reg => reg.MapFrom(o => (o.Group.GroupName ?? string.Empty).Trim()))
              .ForMember(p => p.GroupCategory, reg => reg.MapFrom(o => (o.Group.GroupCategory ?? string.Empty).Trim()))
              .ForMember(p => p.IsApproved, reg => reg.MapFrom(o => o.IsApproved))
              .ForMember(p => p.IsVerified, reg => reg.MapFrom(o => o.IsVerified))
              .ForMember(p => p.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
              .ForMember(p => p.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
              .ForMember(p => p.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
              .ForMember(p => p.ModifiedBy, reg => reg.MapFrom(o => o.LastModifiedBy?? string.Empty))
              .ForMember(p => p.ModifiedOn, reg => reg.MapFrom(o => o.LastModifiedOn ?? o.CreatedOn));

            CreateMap<SystemUser, UserResponse>()
               .ForMember(u =>u.Id, reg => reg.MapFrom(o => o.Id))
               .ForMember(u => u.FirstName, reg => reg.MapFrom(o => (o.FirstName ?? string.Empty).Trim()))
               .ForMember(u => u.MiddleName, reg => reg.MapFrom(o => (o.OtherName ?? string.Empty).Trim()))
               .ForMember(u => u.LastName, reg => reg.MapFrom(o => (o.LastName ?? string.Empty).Trim()))
               .ForMember(u => u.EmailAddress, reg => reg.MapFrom(o => (o.EmailAddress ?? string.Empty).Trim()))
               .ForMember(u => u.PFNumber, reg => reg.MapFrom(o => (o.PFNumber ?? string.Empty).Trim()))
               .ForMember(u => u.PhoneNumber, reg => reg.MapFrom(o => (o.PhoneNumber ?? string.Empty).Trim()))
               .ForMember(u => u.Username, reg => reg.MapFrom(o => (o.Username ?? string.Empty).Trim()))
               .ForMember(u => u.RoleId, reg => reg.MapFrom(o => o.RoleId))
               .ForMember(u =>u.RoleName, reg => reg.MapFrom(o => (o.Role.RoleName ?? string.Empty).Trim()))
               .ForMember(u =>u.SolId, reg => reg.MapFrom(o => (o.BranchSolId ?? string.Empty).Trim()))
               .ForMember(u => u.DepartmentId, reg => reg.MapFrom(o => o.DepartmentId))
               .ForMember(u => u.DepartmentCode, reg => reg.MapFrom(o => (o.Department.DepartmentCode ?? string.Empty).Trim()))
               .ForMember(u => u.DepartmentName, reg => reg.MapFrom(o => (o.Department.DepartmentName ?? string.Empty).Trim()))
               .ForMember(u => u.UnitCode, reg => reg.MapFrom(o => (o.DepartmentUnit ?? string.Empty).Trim()))
               .ForMember(u =>u.IsApproved, reg => reg.MapFrom(o => o.IsApproved))
               .ForMember(u =>u.IsVerified, reg => reg.MapFrom(o => o.IsVerified))
               .ForMember(u =>u.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
               .ForMember(u => u.IsActive, reg => reg.MapFrom(o => o.IsActive))
               .ForMember(u =>u.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
               .ForMember(u =>u.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
               .ForMember(u =>u.ModifiedBy, reg => reg.MapFrom(o => o.LastModifiedBy))
               .ForMember(u =>u.ModifiedOn, reg => reg.MapFrom(o => o.LastModifiedOn))
               .ForMember(u => u.DisplayName, reg => reg.MapFrom(o =>$"{(o.FirstName ?? string.Empty).Trim()} {(o.LastName ?? string.Empty).Trim()}".Trim())); 

            CreateMap<PermissionSetRequest, SystemPermissionSet>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.SetName, reg => reg.MapFrom(o => (o.SetName ?? string.Empty).Trim()))
                .ForMember(r => r.Description, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy))
                .ForMember(r => r.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn));

            CreateMap<SystemPermissionSet, PermissionSetResponse>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.SetName, reg => reg.MapFrom(o => (o.SetName ?? string.Empty).Trim()))
                .ForMember(r => r.SetDescription, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(r => r.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(r => r.CreatedBy, reg => reg.MapFrom(o => (o.CreatedBy ?? string.Empty).Trim()))
                .ForMember(r => r.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
                .ForMember(r => r.ModifiedBy, reg => reg.MapFrom(o => o.LastModifiedBy))
                .ForMember(r => r.ModifiedOn, reg => reg.MapFrom(o => o.LastModifiedOn)); 

            CreateMap<SystemPermission, PermissionResponse>()
                .ForMember(r => r.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(r => r.PermissionName, reg => reg.MapFrom(o => (o.PermissionName ?? string.Empty).Trim()))
                .ForMember(r => r.PermissionDescription, reg => reg.MapFrom(o => (o.Description ?? string.Empty).Trim()))
                .ForMember(r => r.IsAssigned, reg => reg.MapFrom(o => false));

            CreateMap<ActivityLog, SystemActivityResponse>()
                .ForMember(a => a.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(a => a.EntityName, reg => reg.MapFrom(o => (o.EntityName ?? string.Empty).Trim()))
                .ForMember(a => a.ActivityType, reg => reg.MapFrom(o => (o.ActivityType.Name ?? string.Empty).Trim()))
                .ForMember(a => a.IpAddress, reg => reg.MapFrom(o => (o.IpAddress ?? string.Empty).Trim()))
                .ForMember(a => a.Action, reg => reg.MapFrom(o => (o.Comment ?? string.Empty).Trim()))
                .ForMember(a => a.UserId, reg => reg.MapFrom(o => o.UserId))
                .ForMember(a => a.AccessedBy, reg => reg.MapFrom(o => $"{(o.User.FirstName ?? string.Empty).Trim()} {(o.User.LastName ?? string.Empty).Trim()}".Trim()))
                .ForMember(a => a.ActivityDate, reg => reg.MapFrom(o => o.CreatedOn));

            CreateMap<ProcessApprovalRequest, ProcessApproval>()
                .ForMember(a => a.Id, reg => reg.MapFrom(o => o.Id))
                .ForMember(a => a.RequestDate, reg => reg.MapFrom(o => o.RequestDate))
                .ForMember(a => a.HeadOfDepartmentStart, reg => reg.MapFrom(o => o.HODStart))
                .ForMember(a => a.HeadOfDepartmentEnd, reg => reg.MapFrom(o => o.HODEnd))
                .ForMember(a => a.HeadOfDepartmentStatus, reg => reg.MapFrom(o => o.HODStatus))
                .ForMember(a => a.HeadOfDepartmentComment, reg => reg.MapFrom(o => o.HODComment))
                .ForMember(a => a.RiskStart, reg => reg.MapFrom(o => o.RiskStart))
                .ForMember(a => a.RiskEnd, reg => reg.MapFrom(o => o.RiskEnd))
                .ForMember(a => a.RiskStatus, reg => reg.MapFrom(o => o.RiskStatus))
                .ForMember(a => a.RiskComment, reg => reg.MapFrom(o => o.RiskComment))
                .ForMember(a => a.ComplianceStart, reg => reg.MapFrom(o => o.ComplianceStart))
                .ForMember(a => a.ComplianceEnd, reg => reg.MapFrom(o => o.ComplianceEnd))
                .ForMember(a => a.ComplianceStatus, reg => reg.MapFrom(o => o.ComplianceStatus))
                .ForMember(a => a.ComplianceComment, reg => reg.MapFrom(o => o.ComplianceComment))
                .ForMember(a => a.BranchOperationsStatusStart, reg => reg.MapFrom(o => o.BOPStart))
                .ForMember(a => a.BranchOperationsStatusEnd, reg => reg.MapFrom(o => o.BOPEnd))
                .ForMember(a => a.BranchOperationsStatus, reg => reg.MapFrom(o => o.BOPStatus))
                .ForMember(a => a.BranchManagerComment, reg => reg.MapFrom(o => o.ComplianceComment))
                .ForMember(a => a.CreditStart, reg => reg.MapFrom(o => o.CreditStart))
                .ForMember(a => a.CreditEnd, reg => reg.MapFrom(o => o.CreditEnd))
                .ForMember(a => a.CreditStatus, reg => reg.MapFrom(o => o.CreditStatus))
                .ForMember(a => a.CreditComment, reg => reg.MapFrom(o => o.CreditComment))
                .ForMember(a => a.TreasuryStart, reg => reg.MapFrom(o => o.TreasuryStart))
                .ForMember(a => a.TreasuryEnd, reg => reg.MapFrom(o => o.TreasuryEnd))
                .ForMember(a => a.TreasuryStatus, reg => reg.MapFrom(o => o.TreasuryStatus))
                .ForMember(a => a.TreasuryComment, reg => reg.MapFrom(o => o.TreasuryComment))
                .ForMember(a => a.FintechStart, reg => reg.MapFrom(o => o.FintechStart))
                .ForMember(a => a.FintechEnd, reg => reg.MapFrom(o => o.FintechEnd))
                .ForMember(a => a.FintechStatus, reg => reg.MapFrom(o => o.FintechStatus))
                .ForMember(a => a.FintechComment, reg => reg.MapFrom(o => o.FintechComment))
                .ForMember(a => a.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
                .ForMember(a => a.CreatedOn, reg => reg.MapFrom(o => DateTime.Now))
                .ForMember(a => a.CreatedBy, reg => reg.MapFrom(o => o.CreatedBy))
                .ForMember(a => a.LastModifiedOn, reg => reg.MapFrom(o => DateTime.Now))
                .ForMember(a => a.LastModifiedBy, reg => reg.MapFrom(o => o.CreatedBy));

            CreateMap<ProcessGroupRequest, ProcessGroup>()
               .ForMember(g => g.Id, reg => reg.MapFrom(o => o.Id))
               .ForMember(g => g.GroupName, reg => reg.MapFrom(o => (o.GroupName ?? string.Empty).Trim()))
               .ForMember(g => g.Description, reg => reg.MapFrom(o => (o.GroupDescription ?? string.Empty).Trim()))
               .ForMember(g => g.IsDeleted, reg => reg.MapFrom(o => o.IsDeleted))
               .ForMember(g => g.CreatedOn, reg => reg.MapFrom(o => o.CreatedOn))
               .ForMember(g => g.CreatedBy, reg => reg.MapFrom(o => o.CreatedBy))
               .ForMember(g => g.LastModifiedOn, reg => reg.MapFrom(o => o.ModifiedOn))
               .ForMember(g => g.LastModifiedBy, reg => reg.MapFrom(o => o.ModifiedBy));
        }
    }
}
